### ISSUE TITLE
view folder

### ISSUE THREAD

**Issue by gedw99** [charliekim2/chatapp#6]
```sh
chatapp % go mod tidy
go: finding module for package github.com/charliekim2/chatapp/view
go: github.com/charliekim2/chatapp imports
	github.com/charliekim2/chatapp/view: no matching versions for query "latest"
```

We might need a doc.go in the view folder to make golang tooling happy ?

**Comment by gedw99** [comment]
yes that fixed it btw.

**Comment by charliekim2** [comment]
Thanks for the info, fixed

**Comment by gedw99** [comment]
Probably worth generating and committing the .go files that templ generates.

here is a nice task file that does the templ stuff 

https://github.com/delaneyj/datastar/blob/ccce8472eba358b08958e39b583dbe0470b33e98/Taskfile.yml
