### ISSUE TITLE
CSS system 

### ISSUE THREAD

**Issue by gedw99** [charliekim2/chatapp#7]
Have you decided on a css system that leverages tailwind ?

hyper-ui is probably the simplest I have seen. Others are shoelace, daisy, etc 

https://www.hyperui.dev/

I tried a few last night but found them all a little lacking .

**Comment by charliekim2** [comment]
Not 100% sure yet, but I might use Daisy because I like their chat bubble component. WindUI was also something I was looking at.

**Comment by gedw99** [comment]
Ok I am using shoelace at the moment
